permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - released
      - created
      - published

jobs:
  Deploy-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - run: pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
